#!/usr/bin/env bash
# Build and package the named preprint for arXiv using only shell/TeX tools.
# Run from anywhere: bash PAPER_FINAL/iclr2026/package_arxiv.sh
# Optional argument: output .tar.gz path (relative to the caller's directory).
set -euo pipefail

PAPER_DIR="$(cd "$(dirname "$0")" && pwd -P)"
OUTPUT="${1:-$PAPER_DIR/cp2seq-arxiv-source.tar.gz}"
if [[ $# -gt 1 || "$OUTPUT" != *.tar.gz ]]; then
  echo "Usage: $0 [output.tar.gz]" >&2
  exit 2
fi
for tool in pdflatex bibtex tar mktemp; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "Required command not found: $tool" >&2
    exit 1
  }
done
mkdir -p "$(dirname "$OUTPUT")"
OUTPUT="$(cd "$(dirname "$OUTPUT")" && pwd -P)/$(basename "$OUTPUT")"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/cp2seq-arxiv.XXXXXX")"
# Resolve macOS /var -> /private/var so recorder paths compare correctly.
WORK="$(cd "$WORK" && pwd -P)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
BUILD="$WORK/build"
PACKAGE="$WORK/package"
mkdir -p "$BUILD" "$PACKAGE"

# Stage source dependencies; the final package uses the recorder's file list,
# so unused source files, editorial notes, and unused images are not shipped.
cp "$PAPER_DIR"/*.sty "$PAPER_DIR"/*.bib "$PAPER_DIR"/*.bst "$BUILD/"
cp "$PAPER_DIR/math_commands.tex" "$BUILD/"
cp -R "$PAPER_DIR/sections" "$PAPER_DIR/figures" "$PAPER_DIR/listings" "$BUILD/"
{
  printf '%s\n' '% Named arXiv preprint; generated by package_arxiv.sh.'
  printf '%s\n' '\def\arxivversion{1}'
  cat "$PAPER_DIR/iclr2027_conference.tex"
} > "$BUILD/main.tex"

cd "$BUILD"
run_tex() {
  echo "==> pdflatex ($1)"
  if ! pdflatex -no-shell-escape -recorder -interaction=nonstopmode \
      -halt-on-error -file-line-error main.tex > "$WORK/tex-output.txt" 2>&1; then
    cat "$WORK/tex-output.txt" >&2
    exit 1
  fi
}
run_tex 'pass 1/3'
echo '==> bibtex'
if ! bibtex main > "$WORK/bibtex-output.txt" 2>&1; then
  cat "$WORK/bibtex-output.txt" >&2
  exit 1
fi
run_tex 'pass 2/3'
run_tex 'pass 3/3'
if grep -Eq 'There were undefined references|Citation .* undefined|Label\(s\) may have changed' main.log; then
  echo 'ERROR: unresolved references or citations; fix the paper before packaging.' >&2
  exit 1
fi

# Copy only local inputs actually consumed by the successful compilation.
# TeX-distribution files are supplied by arXiv and must not be bundled.
while IFS= read -r line; do
  case "$line" in
    'INPUT '*) file="${line#INPUT }" ;;
    *) continue ;;
  esac
  case "$file" in
    "$BUILD"/*) file="${file#"$BUILD"/}" ;;
    /*) continue ;;
  esac
  file="${file#./}"
  case "/$file/" in
    */../*) echo "ERROR: dependency outside the submission: $file" >&2; exit 1 ;;
  esac
  case "$file" in
    *.aux|*.log|*.out|*.toc|*.fls|*.blg|*.synctex.gz) continue ;;
  esac
  [[ -f "$BUILD/$file" ]] || {
    echo "ERROR: missing recorded dependency: $file" >&2
    exit 1
  }
  mkdir -p "$PACKAGE/$(dirname "$file")"
  cp "$BUILD/$file" "$PACKAGE/$file"
done < main.fls

# BibTeX inputs do not appear in pdflatex's recorder file.
cp main.bbl "$PACKAGE/main.bbl"
cp iclr2027_conference.bib iclr2027_conference.bst "$PACKAGE/"
[[ -s "$PACKAGE/main.tex" && -s "$PACKAGE/main.bbl" ]] || {
  echo 'ERROR: missing main source or compiled bibliography.' >&2
  exit 1
}

# Files live directly at the archive root, preserving all relative paths.
# COPYFILE_DISABLE suppresses macOS AppleDouble metadata entries.
COPYFILE_DISABLE=1 tar -czf "$WORK/source.tar.gz" -C "$PACKAGE" .
tar -tzf "$WORK/source.tar.gz" > /dev/null
mv "$WORK/source.tar.gz" "$OUTPUT"
echo "Created: $OUTPUT"
echo 'Upload this archive to arXiv; select main.tex and PDFLaTeX.'
echo 'Inspect the PDF generated by arXiv before completing submission.'
